### ISSUE TITLE
Stergio ti einai to Strin[] = new String[3]

### ISSUE THREAD

**Issue by nikoszoisse** [mtsio/sem#10]
Mou vazei error otan t trexw.

Exception in thread "Thread-3" java.lang.ArrayIndexOutOfBoundsException: 2
	at application.Workspace.setUpLaw1(Workspace.java:232)
	at application.Workspace.setUpLaws(Workspace.java:59)
	at application.Workspace.<init>(Workspace.java:43)
	at Parser.HistoryParser.requestWorkspace(HistoryParser.java:110)
	at Parser.ParserController.generateWorkspaceFromFile(ParserController.java:35)
	at application.AppManager$1.run(AppManager.java:35)

**Comment by nikoszoisse** [comment]
fixed
